[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
neptune_lbp = "3Wxsikr3N9wJAiKcHfHD5ALyYEogkiGTi2u6nUFm5x3F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/eka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
